apiVersion: v1
kind: Secret
metadata:
  name: dkube-dockerhub-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dkube-deployer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dkube-deployer.imagePullSecretData" . }}