apiVersion: v2
name: dkube-deployer
description: A Kubernetes-based MLOps platform based on open standards Kubeflow and MLflow
home: https://dkube.io
icon: https://www.dkube.io/img/logo_new.png
keywords:
- kubernetes
- MLOps
- Kubeflow
- AI
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.6
# Application version
appVersion: "3.2.0.1"
annotations:
  catalog.cattle.io/certified: partner # Enables the "partner" badge in the UI for easier identification
  catalog.cattle.io/release-name: dkube # Your chart's name in kebab-case, this is used for deployment
  catalog.cattle.io/display-name: Dkube # The chart's name you want displayed in the UI
kubeVersion: "1.20"
